name:                lkirk-xmonad
version:             0.1.0.0
github:              "lkirk/lkirk-xmonad"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/lkirk/lkirk-xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib
- xmobar
- containers
- X11

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
