name: Build XMonad
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required system libraries
        run: |
          sudo apt-get update
          sudo apt-get install
            libx11-dev \
            libxft-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev
      - name: Setup Haskell/Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: '2.7.5'
      - run: stack build
