name: Build XMonad
on: [push]
jobs:
  #  build:
  #    name: Build
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - name: Install required system libraries
  #        run: |
  #          sudo apt-get update
  #          sudo apt-get install \
  #            libx11-dev \
  #            libxft-dev \
  #            libxinerama-dev \
  #            libxrandr-dev \
  #            libxss-dev
  #      - name: Setup Haskell/Stack
  #        uses: haskell/actions/setup@v2
  #        with:
  #          ghc-version: '8.10.7'
  #          enable-stack: true
  #          stack-version: '2.7.5'
  #      - run: stack build

  build-arm64:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build xmonad on arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          # - name: Login to DockerHub
          #   uses: docker/login-action@v1
          #   with:
          #     registry: quay.io
          #     username: ${{ secrets.QUAY_IO_USERNAME }}
          #     password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
